trigger:
- master

variables:
  BuildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  displayName: Instantiate test databases
  inputs:
    containerregistrytype: Container Registry
    dockerComposeFile: docker-compose.yml
    dockerComposeCommand: 'up -d'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: |
      **/*.csproj
      !templates/**/templates/*.csproj
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test (code)
  inputs:
    command: test
    projects: |
      **/*[Tt]ests/*.csproj
      !**/Sample*/**/*.csproj
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test (database - SQL 2017)
  inputs:
    command: test
    projects: |
      **/Sample*[Tt]ests/*.csproj
    arguments: '--configuration $(BuildConfiguration) -s tests/settings/SQL2017.runsettings'
- task: DotNetCoreCLI@2
  displayName: Test (database - SQL 2019)
  inputs:
    command: test
    projects: |
      **/Sample*[Tt]ests/*.csproj
    arguments: '--configuration $(BuildConfiguration) -s tests/settings/SQL2019.runsettings'