trigger:
- master

variables:
  BuildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "$(DefaultConnectionString)"
- script: "##vso[task.setvariable variable=DefaultConnectionString]ABCD"
- script: echo "$(DefaultConnectionString)"