<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
        <PackageReference Include="XUnit" Version="2.9.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Packages.SQLServer.XUnit\Packages.SQLServer.XUnit.csproj" />
	</ItemGroup>

</Project>
