<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8</TargetFramework>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DBConfirm.Packages.SQLServer.XUnit" Version="1.1.0" />
		<PackageReference Include="XUnit" Version="2.9.3" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
	</ItemGroup>

</Project>
