<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8</TargetFramework>

		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DBConfirm.Packages.SQLServer.XUnit" Version="1.*-*" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Packages.SQLServer.XUnit\Packages.SQLServer.XUnit.csproj" />
	</ItemGroup>

</Project>
