name: .NET CI/CD

on:
  pull_request:
    branches:
      - develop
      - main

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -p dbconfirm_test -f docker-compose.yml up -d

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build (main)
        run: |
          for proj in $(find src -name "*.csproj" ! -path "*/templates/templates/*"); do
            dotnet build "$proj" --configuration $BUILD_CONFIGURATION
          done

      - name: Pack NuGet packages
        run: |
          for proj in $(find src -name "*.csproj" ! -path "*/templates/templates/*"); do
            dotnet pack "$proj" --configuration $BUILD_CONFIGURATION /p:Version=1.0.1-prerelease
          done

      - name: Push NuGet packages
        run: |
          for file in $(find . -name '*.nupkg' ! -name '*.Tests.nupkg'); do
            dotnet nuget push "$file" \
              --source "https://pkgs.dev.azure.com/bungalow64/_packaging/bungalow64/nuget/v3/index.json" \
              --api-key ${{ secrets.AZURE_DEVOPS_TOKEN }} \
              --skip-duplicate
          done

      - name: Restore (NuGet - after push)
        run: |
          for proj in $(find . -path "./NuGet" -prune -o -name "*.csproj" -path "*NuGet*" -print); do
            dotnet restore "$proj" --source "https://pkgs.dev.azure.com/bungalow64/_packaging/bungalow64/nuget/v3/index.json"
          done

      - name: Build (NuGet)
        continue-on-error: true
        run: |
          for proj in $(find . -path "*NuGet*" -name "*.csproj"); do
            dotnet build "$proj" \
              --configuration ${{ env.BUILD_CONFIGURATION }} \
              --no-restore \
              /p:EmitCompilerGeneratedFiles=true \
              /p:CompilerGeneratedFilesOutputPath=$(pwd)/GeneratedFiles
          done

      - name: Run Unit Tests
        run: |
          for proj in $(find . -name "*[Tt]ests*.csproj" ! -path "*Sample*"); do
            dotnet test "$proj" --configuration ${{ env.BUILD_CONFIGURATION }} || true
          done

      - name: Test Projects (SQL 2017)
        run: |
          for proj in $(find . -path "*Sample*[Tt]ests*" -name "*.csproj" ! -path "*NuGet*"); do
            dotnet test "$proj" --configuration ${{ env.BUILD_CONFIGURATION }} -s tests/Settings/SQL2017.runsettings || true
          done
          for proj in $(find . -path "*NuGet/Sample*[Tt]ests*" -name "*.csproj"); do
            dotnet test "$proj" --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore -s tests/Settings/SQL2017.runsettings || true
          done

      - name: Test Projects (SQL 2019)
        run: |
          for proj in $(find . -path "*Sample*[Tt]ests*" -name "*.csproj" ! -path "*NuGet*"); do
            dotnet test "$proj" --configuration ${{ env.BUILD_CONFIGURATION }} -s tests/Settings/SQL2019.runsettings || true
          done
          for proj in $(find . -path "*NuGet/Sample*[Tt]ests*" -name "*.csproj"); do
            dotnet test "$proj" --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore -s tests/Settings/SQL2019.runsettings || true
          done

      - name: Test Projects (SQL 2022)
        run: |
          for proj in $(find . -path "*Sample*[Tt]ests*" -name "*.csproj" ! -path "*NuGet*"); do
            dotnet test "$proj" --configuration ${{ env.BUILD_CONFIGURATION }} -s tests/Settings/SQL2022.runsettings || true
          done
          for proj in $(find . -path "*NuGet/Sample*[Tt]ests*" -name "*.csproj"); do
            dotnet test "$proj" --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore -s tests/Settings/SQL2022.runsettings || true
          done
